name: CD
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: |
            echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > keypair.pem
            chmod 600 keypair.pem
          script: |
            cd /home/ubuntu/task4/fastapi-book-project
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            pm2 restart fastapi-app || pm2 start gunicorn --name fastapi-app -- -w 4 -k uvicorn.workers.UvicornWorker main:app
