name: CD
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > keypair.pem
          chmod 600 keypair.pem
          mkdir -p ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null" >> ~/.ssh/config
      
      - name: Test SSH connection (Verbose)
        run: |
          ssh -v -i keypair.pem ubuntu@${{ secrets.SERVER_IP }} exit
      
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/task4/fastapi-book-project
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            pm2 restart fastapi-app || pm2 start gunicorn --name fastapi-app -- -w 4 -k uvicorn.workers.UvicornWorker main:app
